### ISSUE TITLE
error JPG Decompression Failed

### ISSUE THREAD

**Issue by nechry** [MikaelBertze/HallonDispDevices#1]
Hello,

I try to use your solution. I order ESP32-CAM and prog the ESP but I just get this error non stop
`
[E][esp_jpg_decode.c:108] esp_jpg_decode(): JPG Decompression Failed! Device error or wrong termination of input stream
`
Did you also get this error?
Is something related to the calibration step?

many thank for your help

**Comment by MikaelBertze** [comment]
I've seen this in my setup too, and I have also found other threads describing the same.

I just ignored it. The image is still retrieved, but I think this is why there last two lones of pixels are missing. The error is not from my code, so you might get a better response from the people involved in the esp32-camera repo. https://github.com/espressif/esp32-camera

**Comment by nechry** [comment]
in the camera setup we can add 
`config.jpeg_quality = 10;`
and the error disappear for me.

**Comment by nechry** [comment]
@MikaelBertze can I ask-you the web route /calibrate is supposed to return an image file? I juste have to rename the file calibrate to /calibrate.jpg ? The body content didn't correspond to an image file
![calibrate](https://user-images.githubusercontent.com/307966/108607079-61663200-73be-11eb-9da5-0b47547c26ba.jpeg)

**Comment by MikaelBertze** [comment]
You receive an octet stream of RGB values. I've uses matplotlib (python) to display the image.

**Comment by MikaelBertze** [comment]
> in the camera setup we can add
> `config.jpeg_quality = 10;`
> and the error disappear for me.

Thank you for the info. I will try it out.

**Comment by MikaelBertze** [comment]
Here is a python snippet I use for calibration
I run this in jupyter notebook.
```
import requests
import matplotlib.pyplot as plt
import numpy as np
%matplotlib inline

for i in range(3):

    r = requests.get(f"http://192.168.50.211/image/{i}")
    print(r)

    w = int(r.headers['w'])
    h = int(r.headers['h'])
    c = int(r.headers['c'])
    print(r.headers)
    data = np.frombuffer(r.content, dtype=np.uint8)
    if c == 1:
        fullimage = data.reshape(h, w)
        plt.figure(figsize = (10,10))
        plt.imshow(fullimage)
    else:
        fullimage = data.reshape(h, w, c)
        image = fullimage[:,:,[2,1,0]]
        plt.figure(figsize = (10,10))
        plt.imshow(image)
        plt.show()
```

To change the parameters

```
x = 95
y = 49
w = 161
r = requests.get(f"http://192.168.50.211/set/capture_x/{x}")
print(r.text)
r = requests.get(f"http://192.168.50.211/set/capture_y/{y}")
print(r.text)
r = requests.get(f"http://192.168.50.211/set/capture_size/{w}")
print(r.text)
r = requests.get("http://192.168.50.211/set/filter_start/20")
print(r.text)
r = requests.get("http://192.168.50.211/set/filter_length/58")
print(r.text)

```

**Comment by nechry** [comment]
ha, great now I understand better and with your python script I can decode image. I will set on my meter and hop I can also get measurement.
